//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsServiceReference.ServiceSoap")]
    public interface ServiceSoap
    {
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        SmsServiceReference.SendSMSResponse SendSMS(SmsServiceReference.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsServiceReference.SendSMSResponse> SendSMSAsync(SmsServiceReference.SendSMSRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS_new", ReplyAction="*")]
        SmsServiceReference.SendSMS_newResponse SendSMS_new(SmsServiceReference.SendSMS_newRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS_new", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsServiceReference.SendSMS_newResponse> SendSMS_newAsync(SmsServiceReference.SendSMS_newRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendGemaltoSMS", ReplyAction="*")]
        SmsServiceReference.SendGemaltoSMSResponse SendGemaltoSMS(SmsServiceReference.SendGemaltoSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendGemaltoSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsServiceReference.SendGemaltoSMSResponse> SendGemaltoSMSAsync(SmsServiceReference.SendGemaltoSMSRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSIB", ReplyAction="*")]
        SmsServiceReference.SendSMSIBResponse SendSMSIB(SmsServiceReference.SendSMSIBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSIB", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsServiceReference.SendSMSIBResponse> SendSMSIBAsync(SmsServiceReference.SendSMSIBRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS_OTP", ReplyAction="*")]
        SmsServiceReference.SendSMS_OTPResponse SendSMS_OTP(SmsServiceReference.SendSMS_OTPRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS_OTP", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsServiceReference.SendSMS_OTPResponse> SendSMS_OTPAsync(SmsServiceReference.SendSMS_OTPRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSBangla", ReplyAction="*")]
        SmsServiceReference.SendSMSBanglaResponse SendSMSBangla(SmsServiceReference.SendSMSBanglaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSBangla", ReplyAction="*")]
        System.Threading.Tasks.Task<SmsServiceReference.SendSMSBanglaResponse> SendSMSBanglaAsync(SmsServiceReference.SendSMSBanglaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="http://tempuri.org/", Order=0)]
        public SmsServiceReference.SendSMSRequestBody Body;
        
        public SendSMSRequest()
        {
        }
        
        public SendSMSRequest(SmsServiceReference.SendSMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mobileNo;
        
        public SendSMSRequestBody()
        {
        }
        
        public SendSMSRequestBody(string userId, string password, string message, string mobileNo)
        {
            this.userId = userId;
            this.password = password;
            this.message = message;
            this.mobileNo = mobileNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmsServiceReference.SendSMSResponseBody Body;
        
        public SendSMSResponse()
        {
        }
        
        public SendSMSResponse(SmsServiceReference.SendSMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMSResult;
        
        public SendSMSResponseBody()
        {
        }
        
        public SendSMSResponseBody(string SendSMSResult)
        {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMS_newRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS_new", Namespace="http://tempuri.org/", Order=0)]
        public SmsServiceReference.SendSMS_newRequestBody Body;
        
        public SendSMS_newRequest()
        {
        }
        
        public SendSMS_newRequest(SmsServiceReference.SendSMS_newRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMS_newRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mobileNo;
        
        public SendSMS_newRequestBody()
        {
        }
        
        public SendSMS_newRequestBody(string userId, string password, string message, string mobileNo)
        {
            this.userId = userId;
            this.password = password;
            this.message = message;
            this.mobileNo = mobileNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMS_newResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS_newResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmsServiceReference.SendSMS_newResponseBody Body;
        
        public SendSMS_newResponse()
        {
        }
        
        public SendSMS_newResponse(SmsServiceReference.SendSMS_newResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMS_newResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMS_newResult;
        
        public SendSMS_newResponseBody()
        {
        }
        
        public SendSMS_newResponseBody(string SendSMS_newResult)
        {
            this.SendSMS_newResult = SendSMS_newResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendGemaltoSMSRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendGemaltoSMS", Namespace="http://tempuri.org/", Order=0)]
        public SmsServiceReference.SendGemaltoSMSRequestBody Body;
        
        public SendGemaltoSMSRequest()
        {
        }
        
        public SendGemaltoSMSRequest(SmsServiceReference.SendGemaltoSMSRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendGemaltoSMSRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mobileNo;
        
        public SendGemaltoSMSRequestBody()
        {
        }
        
        public SendGemaltoSMSRequestBody(string userId, string password, string message, string mobileNo)
        {
            this.userId = userId;
            this.password = password;
            this.message = message;
            this.mobileNo = mobileNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendGemaltoSMSResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendGemaltoSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmsServiceReference.SendGemaltoSMSResponseBody Body;
        
        public SendGemaltoSMSResponse()
        {
        }
        
        public SendGemaltoSMSResponse(SmsServiceReference.SendGemaltoSMSResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendGemaltoSMSResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendGemaltoSMSResult;
        
        public SendGemaltoSMSResponseBody()
        {
        }
        
        public SendGemaltoSMSResponseBody(string SendGemaltoSMSResult)
        {
            this.SendGemaltoSMSResult = SendGemaltoSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSIBRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSIB", Namespace="http://tempuri.org/", Order=0)]
        public SmsServiceReference.SendSMSIBRequestBody Body;
        
        public SendSMSIBRequest()
        {
        }
        
        public SendSMSIBRequest(SmsServiceReference.SendSMSIBRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSIBRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mobileNo;
        
        public SendSMSIBRequestBody()
        {
        }
        
        public SendSMSIBRequestBody(string userId, string password, string message, string mobileNo)
        {
            this.userId = userId;
            this.password = password;
            this.message = message;
            this.mobileNo = mobileNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSIBResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSIBResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmsServiceReference.SendSMSIBResponseBody Body;
        
        public SendSMSIBResponse()
        {
        }
        
        public SendSMSIBResponse(SmsServiceReference.SendSMSIBResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSIBResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMSIBResult;
        
        public SendSMSIBResponseBody()
        {
        }
        
        public SendSMSIBResponseBody(string SendSMSIBResult)
        {
            this.SendSMSIBResult = SendSMSIBResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMS_OTPRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS_OTP", Namespace="http://tempuri.org/", Order=0)]
        public SmsServiceReference.SendSMS_OTPRequestBody Body;
        
        public SendSMS_OTPRequest()
        {
        }
        
        public SendSMS_OTPRequest(SmsServiceReference.SendSMS_OTPRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMS_OTPRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mobileNo;
        
        public SendSMS_OTPRequestBody()
        {
        }
        
        public SendSMS_OTPRequestBody(string userId, string password, string message, string mobileNo)
        {
            this.userId = userId;
            this.password = password;
            this.message = message;
            this.mobileNo = mobileNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMS_OTPResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS_OTPResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmsServiceReference.SendSMS_OTPResponseBody Body;
        
        public SendSMS_OTPResponse()
        {
        }
        
        public SendSMS_OTPResponse(SmsServiceReference.SendSMS_OTPResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMS_OTPResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMS_OTPResult;
        
        public SendSMS_OTPResponseBody()
        {
        }
        
        public SendSMS_OTPResponseBody(string SendSMS_OTPResult)
        {
            this.SendSMS_OTPResult = SendSMS_OTPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSBanglaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSBangla", Namespace="http://tempuri.org/", Order=0)]
        public SmsServiceReference.SendSMSBanglaRequestBody Body;
        
        public SendSMSBanglaRequest()
        {
        }
        
        public SendSMSBanglaRequest(SmsServiceReference.SendSMSBanglaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSBanglaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string mobileNo;
        
        public SendSMSBanglaRequestBody()
        {
        }
        
        public SendSMSBanglaRequestBody(string userId, string password, string message, string mobileNo)
        {
            this.userId = userId;
            this.password = password;
            this.message = message;
            this.mobileNo = mobileNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSBanglaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSBanglaResponse", Namespace="http://tempuri.org/", Order=0)]
        public SmsServiceReference.SendSMSBanglaResponseBody Body;
        
        public SendSMSBanglaResponse()
        {
        }
        
        public SendSMSBanglaResponse(SmsServiceReference.SendSMSBanglaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSBanglaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMSBanglaResult;
        
        public SendSMSBanglaResponseBody()
        {
        }
        
        public SendSMSBanglaResponseBody(string SendSMSBanglaResult)
        {
            this.SendSMSBanglaResult = SendSMSBanglaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ServiceSoapChannel : SmsServiceReference.ServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<SmsServiceReference.ServiceSoap>, SmsServiceReference.ServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsServiceReference.SendSMSResponse SmsServiceReference.ServiceSoap.SendSMS(SmsServiceReference.SendSMSRequest request)
        {
            return base.Channel.SendSMS(request);
        }
        
        public string SendSMS(string userId, string password, string message, string mobileNo)
        {
            SmsServiceReference.SendSMSRequest inValue = new SmsServiceReference.SendSMSRequest();
            inValue.Body = new SmsServiceReference.SendSMSRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.message = message;
            inValue.Body.mobileNo = mobileNo;
            SmsServiceReference.SendSMSResponse retVal = ((SmsServiceReference.ServiceSoap)(this)).SendSMS(inValue);
            return retVal.Body.SendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceReference.SendSMSResponse> SmsServiceReference.ServiceSoap.SendSMSAsync(SmsServiceReference.SendSMSRequest request)
        {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceReference.SendSMSResponse> SendSMSAsync(string userId, string password, string message, string mobileNo)
        {
            SmsServiceReference.SendSMSRequest inValue = new SmsServiceReference.SendSMSRequest();
            inValue.Body = new SmsServiceReference.SendSMSRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.message = message;
            inValue.Body.mobileNo = mobileNo;
            return ((SmsServiceReference.ServiceSoap)(this)).SendSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsServiceReference.SendSMS_newResponse SmsServiceReference.ServiceSoap.SendSMS_new(SmsServiceReference.SendSMS_newRequest request)
        {
            return base.Channel.SendSMS_new(request);
        }
        
        public string SendSMS_new(string userId, string password, string message, string mobileNo)
        {
            SmsServiceReference.SendSMS_newRequest inValue = new SmsServiceReference.SendSMS_newRequest();
            inValue.Body = new SmsServiceReference.SendSMS_newRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.message = message;
            inValue.Body.mobileNo = mobileNo;
            SmsServiceReference.SendSMS_newResponse retVal = ((SmsServiceReference.ServiceSoap)(this)).SendSMS_new(inValue);
            return retVal.Body.SendSMS_newResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceReference.SendSMS_newResponse> SmsServiceReference.ServiceSoap.SendSMS_newAsync(SmsServiceReference.SendSMS_newRequest request)
        {
            return base.Channel.SendSMS_newAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceReference.SendSMS_newResponse> SendSMS_newAsync(string userId, string password, string message, string mobileNo)
        {
            SmsServiceReference.SendSMS_newRequest inValue = new SmsServiceReference.SendSMS_newRequest();
            inValue.Body = new SmsServiceReference.SendSMS_newRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.message = message;
            inValue.Body.mobileNo = mobileNo;
            return ((SmsServiceReference.ServiceSoap)(this)).SendSMS_newAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsServiceReference.SendGemaltoSMSResponse SmsServiceReference.ServiceSoap.SendGemaltoSMS(SmsServiceReference.SendGemaltoSMSRequest request)
        {
            return base.Channel.SendGemaltoSMS(request);
        }
        
        public string SendGemaltoSMS(string userId, string password, string message, string mobileNo)
        {
            SmsServiceReference.SendGemaltoSMSRequest inValue = new SmsServiceReference.SendGemaltoSMSRequest();
            inValue.Body = new SmsServiceReference.SendGemaltoSMSRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.message = message;
            inValue.Body.mobileNo = mobileNo;
            SmsServiceReference.SendGemaltoSMSResponse retVal = ((SmsServiceReference.ServiceSoap)(this)).SendGemaltoSMS(inValue);
            return retVal.Body.SendGemaltoSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceReference.SendGemaltoSMSResponse> SmsServiceReference.ServiceSoap.SendGemaltoSMSAsync(SmsServiceReference.SendGemaltoSMSRequest request)
        {
            return base.Channel.SendGemaltoSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceReference.SendGemaltoSMSResponse> SendGemaltoSMSAsync(string userId, string password, string message, string mobileNo)
        {
            SmsServiceReference.SendGemaltoSMSRequest inValue = new SmsServiceReference.SendGemaltoSMSRequest();
            inValue.Body = new SmsServiceReference.SendGemaltoSMSRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.message = message;
            inValue.Body.mobileNo = mobileNo;
            return ((SmsServiceReference.ServiceSoap)(this)).SendGemaltoSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsServiceReference.SendSMSIBResponse SmsServiceReference.ServiceSoap.SendSMSIB(SmsServiceReference.SendSMSIBRequest request)
        {
            return base.Channel.SendSMSIB(request);
        }
        
        public string SendSMSIB(string userId, string password, string message, string mobileNo)
        {
            SmsServiceReference.SendSMSIBRequest inValue = new SmsServiceReference.SendSMSIBRequest();
            inValue.Body = new SmsServiceReference.SendSMSIBRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.message = message;
            inValue.Body.mobileNo = mobileNo;
            SmsServiceReference.SendSMSIBResponse retVal = ((SmsServiceReference.ServiceSoap)(this)).SendSMSIB(inValue);
            return retVal.Body.SendSMSIBResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceReference.SendSMSIBResponse> SmsServiceReference.ServiceSoap.SendSMSIBAsync(SmsServiceReference.SendSMSIBRequest request)
        {
            return base.Channel.SendSMSIBAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceReference.SendSMSIBResponse> SendSMSIBAsync(string userId, string password, string message, string mobileNo)
        {
            SmsServiceReference.SendSMSIBRequest inValue = new SmsServiceReference.SendSMSIBRequest();
            inValue.Body = new SmsServiceReference.SendSMSIBRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.message = message;
            inValue.Body.mobileNo = mobileNo;
            return ((SmsServiceReference.ServiceSoap)(this)).SendSMSIBAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsServiceReference.SendSMS_OTPResponse SmsServiceReference.ServiceSoap.SendSMS_OTP(SmsServiceReference.SendSMS_OTPRequest request)
        {
            return base.Channel.SendSMS_OTP(request);
        }
        
        public string SendSMS_OTP(string userId, string password, string message, string mobileNo)
        {
            SmsServiceReference.SendSMS_OTPRequest inValue = new SmsServiceReference.SendSMS_OTPRequest();
            inValue.Body = new SmsServiceReference.SendSMS_OTPRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.message = message;
            inValue.Body.mobileNo = mobileNo;
            SmsServiceReference.SendSMS_OTPResponse retVal = ((SmsServiceReference.ServiceSoap)(this)).SendSMS_OTP(inValue);
            return retVal.Body.SendSMS_OTPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceReference.SendSMS_OTPResponse> SmsServiceReference.ServiceSoap.SendSMS_OTPAsync(SmsServiceReference.SendSMS_OTPRequest request)
        {
            return base.Channel.SendSMS_OTPAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceReference.SendSMS_OTPResponse> SendSMS_OTPAsync(string userId, string password, string message, string mobileNo)
        {
            SmsServiceReference.SendSMS_OTPRequest inValue = new SmsServiceReference.SendSMS_OTPRequest();
            inValue.Body = new SmsServiceReference.SendSMS_OTPRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.message = message;
            inValue.Body.mobileNo = mobileNo;
            return ((SmsServiceReference.ServiceSoap)(this)).SendSMS_OTPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsServiceReference.SendSMSBanglaResponse SmsServiceReference.ServiceSoap.SendSMSBangla(SmsServiceReference.SendSMSBanglaRequest request)
        {
            return base.Channel.SendSMSBangla(request);
        }
        
        public string SendSMSBangla(string userId, string password, string message, string mobileNo)
        {
            SmsServiceReference.SendSMSBanglaRequest inValue = new SmsServiceReference.SendSMSBanglaRequest();
            inValue.Body = new SmsServiceReference.SendSMSBanglaRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.message = message;
            inValue.Body.mobileNo = mobileNo;
            SmsServiceReference.SendSMSBanglaResponse retVal = ((SmsServiceReference.ServiceSoap)(this)).SendSMSBangla(inValue);
            return retVal.Body.SendSMSBanglaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmsServiceReference.SendSMSBanglaResponse> SmsServiceReference.ServiceSoap.SendSMSBanglaAsync(SmsServiceReference.SendSMSBanglaRequest request)
        {
            return base.Channel.SendSMSBanglaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmsServiceReference.SendSMSBanglaResponse> SendSMSBanglaAsync(string userId, string password, string message, string mobileNo)
        {
            SmsServiceReference.SendSMSBanglaRequest inValue = new SmsServiceReference.SendSMSBanglaRequest();
            inValue.Body = new SmsServiceReference.SendSMSBanglaRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.message = message;
            inValue.Body.mobileNo = mobileNo;
            return ((SmsServiceReference.ServiceSoap)(this)).SendSMSBanglaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://172.31.100.100/smsservice/Service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://172.31.100.100/smsservice/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ServiceSoap,
            
            ServiceSoap12,
        }
    }
}
